[Greeter]
  exced = true
  log_level = "debug"
  [Greeter.tgrpc]
    address = "localhost:2080"
    reuse_desc = true
    proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
    include_imports = "helloworld/helloworld.proto"
    keepalive = "100s"

  [[Greeter.invokes]]
    method = "helloworld.Greeter/SayHello"
    headers = ["customerId:123", "region:UK"]
    data = "{\"name\":\"tgrpc-tg1\"}"
    n = 5
    interval = "200ms"
    [Greeter.invokes.resp]
      cost = "500ms"
      [Greeter.invokes.resp.json]
        message = "Hello tgrpc-tg1"
