[Greeter]
exced = true
[Greeter.tgrpc]
  address = "localhost:2080"
  reuse_desc = false
  proto_base_path = "$GOPATH/src/github.com/toukii/ngrpc"
  include_imports = "helloworld/helloworld.proto"
  keepalive = "100s"

[[Greeter.invokes]]
  exced = true
  method = "helloworld.Greeter/SayHello"
  headers = ["customerId:123", "region:UK"]
  data = "{\"name\":\"tgrpc-tg1\"}"

[[Greeter.invokes]]
  exced = false
  method = "helloworld.Greeter/SayHello"
  headers = ["customerId:345", "region:UK"]
  data = "{\"name\":\"tgrpc-tg2\"}"
