log_level = "debug"
[service]
[service.Greeter]
address = "localhost:2080"
reuse_desc = true
proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
include_imports = "helloworld/helloworld.proto"
keepalive = "100s"
data = '{"vals":["1","2","3"]}'
raw_desc = '0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88, 0x28, 0x29, 0x71, 0xf1, 0x78, 0x80, 0x78, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x1a, 0x17, 0x17, 0x54, 0x4d, 0x41, 0x4e, 0xa5, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x11, 0x8c, 0x6b, 0xe4, 0xc9, 0xc5, 0xee, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x5a, 0x24, 0x64, 0xc7, 0xc5, 0x11, 0x9c, 0x58, 0x09, 0xd6, 0x25, 0x24, 0xa1, 0x87, 0xe4, 0x02, 0x64, 0xcb, 0xa4, 0xc4, 0xb0, 0xc8, 0x14, 0xe4, 0x54, 0x2a, 0x31, 0x38, 0x39, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x33, 0x1e, 0xcb, 0x31, 0x70, 0x49, 0x67, 0xe6, 0xeb, 0xa5, 0x17, 0x15, 0x24, 0xeb, 0xa5, 0x56, 0x24, 0xe6, 0x16, 0xe4, 0xa4, 0x16, 0x23, 0xe9, 0x75, 0xe2, 0x07, 0x6b, 0x0e, 0x07, 0xb1, 0x03, 0x40, 0x5e, 0x0c, 0x60, 0x4c, 0x62, 0x03, 0xfb, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x02, 0xdd, 0xb3, 0x0e, 0xff, 0x00, 0x00, 0x00,'

[service.Language]
address = "localhost:2080"
reuse_desc = true
proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
include_imports = "helloworld/lang.proto"
keepalive = "100s"
data = '["1", "2", "3"]'

[[invokes]]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = '{"name":"$range"}'
n = 1

[[invokes]]
service= "Language"
method = "helloworld.LangService/List"
headers = ["customerId:123", "region:UK"]
data = '{}'
n = 1
interval = "200ms"
[invokes.next]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = '{"name":"@langs,$range,versions,0,desc"}'
n = 1

[[invokes]]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = '{"name":"@vals,$range"}'
n = 1
interval = "200ms"
[invokes.resp]
cost = "2ms"
# [invokes.resp.json]
# message = "Hello 1"

[[invokes]]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = "{\"name\":\"tgrpc-tg1\"}"
n = 1
interval = "200ms"
[invokes.resp]
cost = "2ms"
[invokes.resp.json]
message = "Hello tgrpc-tg1"

[[invokes]]
service= "Language"
method = "helloworld.LangService/List"
headers = ["customerId:123", "region:UK"]
data = '{}'
n = 1
interval = "200ms"
[invokes.resp]
cost = "2ms"
[invokes.resp.json]
'langs,0,birthday' = 1136185445.0
totalCount = 999.0
'langs,1,versions,0,id' = 700.0
'langs,1,versions,0,vi32s,0' = 111.0
'langs,1,versions,0,vi32s' = [111.0,222.0]
'langs,1,versions,0,vi64s,0' = 111.0
'langs,1,versions,0,vi64s' = [111.0,222.0]
'langs,1,versions,0,vf64s,0' = 111.0
'langs,1,versions,0,vf64s' = [111.0,222.0]
'langs,1,versions,0,vstrs,0' = 'str1'
'langs,1,versions,0,vstrs' = ['str1','str2']
'langs,1,versions,0,vstrs,$len' = 2
[invokes.next]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = '{"name":"@langs,0,versions,0,vstrs,$range"}'
n = 1
interval = "500ms"
[invokes.next.resp]
cost = "2ms"
[[invokes.then]]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = "{\"name\":\"tgrpc-tg--then\"}"
n = 3
interval = "500ms"
[invokes.then.resp]
cost = "2ms"
